//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzurePerformanceV4
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;


    [Priority(0)]
    public class logintestdemoCoded : WebTest
    {

        public logintestdemoCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest("http://ocsp.godaddy.com//MEIwQDA%2BMDwwOjAJBgUrDgMCGgUABBQdI2%2BOBkuXH93foRUj4a7l" +
                    "Ar4rGwQUOpqFBxBnKLbv9r0FQW4gwZTaD94CAQc%3D");
            request1.Timeout = 60;
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://ocsp.godaddy.com//MEowSDBGMEQwQjAJBgUrDgMCGgUABBS2CA1fbGt26xPkOKX4ZguoUjM0" +
                    "TgQUQMK9J47MNIMwojPX%2B2yz8LQsgM4CCQD18CbxWi248w%3D%3D");
            request2.Timeout = 60;
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("https://cdn2.moneycorp.com/abF4cfM3jbBmpbOb");
            request3.Timeout = 60;
            request3.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request3.QueryStringParameters.Add("45f401920459995f", "hnKPdxa6Wi-LAVO9jCznhg1lUuWlZfJECpgMtbkKcySBjvJUfXWNgDcrExhuWyjgEhwx9VPzp_x69m3YG" +
                    "QgE2FC7DmDVuuHm4TV-zr3GapHCR88D-WMKDSZaMo8KLoP_k7ZlHfCgtqfMowf1R39nuOsTdMM");
            request3.QueryStringParameters.Add("jf", "313e266c73623f396c376b35643a616162323b346338346a633135633334643130383163316b31");
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("https://cdn2.moneycorp.com/lUX68XqnKQpkKheM");
            request4.Timeout = 60;
            request4.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request4.QueryStringParameters.Add("27cd0d459b871af1", "57hqyySVPwIyBm8ev-Q1UCSZc5GJZ9qt1VqO--ictLYPdI_2Tsn6D8p-xT4G5P6V1tz46KOHjwhfR8cw-" +
                    "7NshGESQn7d80agcp943I9hfunJI-avYlJEF3SiB8LAbH4DJXETWZAIR8hwBK0H_oQk1fzLWg0");
            request4.QueryStringParameters.Add("jac", "1");
            request4.QueryStringParameters.Add("je", "342e26706d3d6c6f");
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("https://cdn2.moneycorp.com/LwAcyJYtrR5ijN78");
            request5.Timeout = 60;
            request5.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request5.QueryStringParameters.Add("9fac97936fa787dc", "hOOooBAOvMKA3urNl_lTrtIe2XtZhYF4wfP79VpE2G8BnblQan91lz5ImaY83jKaLoJ57kvpDhd_Ne6qF" +
                    "elPzsGQBN-955lEhBtWrYspHTfMHHxQt7s6D2AYfaYFh5IJl_eKOiFyryAzlVJq7BxRIaP9UTcMT9xTh" +
                    "3HF9lJxLV9eH1-5tnEaAR02HM_WYBwhxZPy4RqbXsdJKJ95BneTMg_vlIM");
            request5.QueryStringParameters.Add("sera_parametere", @"BUMLCFdVAlVWD1cEV1IOAVsGVQpTBgRXA1NVAVsBDlEGC1UAUFoABlAPUhERRwUNDUNDTRBHBncQASYSVXAdVlNZRVwPB1hWW0IXElFwHVMhAxMOJ0cHA11ZF0MREQsgRgR0HFQmE1dcC11UUFcIV1MDVwkBA1FQUFNSBwcAAFZWBgMIVlcHVwUFUVYDDVtQVwAQVwwMVlYIVVcBW1daUVAGAF1UAAELURAORF8EQFcGBFQNBlUFClNXAVFWUQtQAlYECAVXBgBQV1FSAwxaBlAEVF1VVQwVVF9ZBlIGAFNFWl8ETlMTQ1wLXQ5bDQBCC1gLHwFfcEtFWgtFB0YeBhUOBwhFAFpACGENWQZbTxdFUFQEFwZPbFZXCFsAVVsPRVZCBFRQ");
            request5.QueryStringParameters.Add("count", "0");
            request5.QueryStringParameters.Add("max", "0");
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("https://aa.online-metrix.net/fpc.swf");
            request6.Timeout = 60;
            request6.Headers.Add(new WebTestRequestHeader("x-flash-version", "32,0,0,445"));
            request6.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request6.QueryStringParameters.Add("session", "f851dd64-192c-4644-a592-20507f74ed10");
            request6.QueryStringParameters.Add("org", "ac9enyev");
            request6.QueryStringParameters.Add("nu", "11775");
            request6.QueryStringParameters.Add("fx", "3a312675726c3f687c74787138272f61646e3a2e6d676c6d7b636f72722c616f6d2f66702d2e66673" +
                    "d373a666e396935313b336162343e663231323b646466653760603839346436632e773d633334396" +
                    "b623d31373e643562343064");
            request6.QueryStringParameters.Add("fy", "353e2626763d554946203b302e382c322c343c3526673f5f6b6e646f757122313026667471663d323" +
                    "43124667c73353b643d306739303b35326b333f32623939333660343032623231383364393230");
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("https://cdn2.moneycorp.com/crossdomain.xml");
            request7.Timeout = 60;
            request7.Headers.Add(new WebTestRequestHeader("x-flash-version", "32,0,0,445"));
            request7.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("https://iecvlist.microsoft.com/ie11blocklist/1401746408/versionlist.xml");
            request8.ThinkTime = 2;
            request8.Timeout = 60;
            request8.Headers.Add(new WebTestRequestHeader("If-Modified-Since", "Tue, 20 Aug 2019 20:56:35 GMT"));
            request8.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("https://qa-ids.moneycorp.com/login/validateCredentials");
            request9.ThinkTime = -5;
            request9.Timeout = 60;
            request9.Method = "POST";
            request9.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
            request9.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            StringHttpBody request9Body = new StringHttpBody();
            request9Body.ContentType = "application/json";
            request9Body.InsertByteOrderMark = false;
            request9Body.BodyString = "{\"username\":\"puser1\",\"password\":\"Moneycorp0\",\"mobileOs\":\"\",\"threatMetrixToken\":\"f" +
                "851dd64-192c-4644-a592-20507f74ed10\",\"ssoClientName\":\"imaliClient\",\"loginDeviceS" +
                "ource\":\"browser_computer\"}";
            request9.Body = request9Body;
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("https://cdn2.moneycorp.com/Oddwdc_sx8qEVxQJ");
            request10.Timeout = 60;
            request10.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request10.QueryStringParameters.Add("8e85fa6ec1614899", "kAOGCRRmGus5po2gRitC7YbLUPpo_MqXjF7BVw-1FBdwaHPWWZBrtIyHUBfjKEbuIMpzJcyw_MQVksPNL" +
                    "eDdc6wPqH31nQL0K5yLcWRb24JU0u0TftkPvj1fn3S0GisWj6c0rQuakR2DCK98hu06oc8ZYBrzCLUWN" +
                    "wiZSx5xMyxUY9w2ACFIE_zqn73zlElTIg4mpszWs78VAIH_Fpk");
            request10.QueryStringParameters.Add("je", @"3039382672643f267a647c3f343b3331332d7d6e646d64616c65642c373b32302d756e64676e696e65642e353130392f77666467666966656424373132322d756c666766696e65642e3d3930332d776e6c656e6b6c6d642e333330392d7d6c6c6766696e67662e353935302d7766646566696c656c2c3d3b31392d776e646d666966676c2e3539333b2f776e646566696c6d642c3630313925756666676e696c65642435393c3625776e6465646b6c65642c363036382d756e646766616e6d662e3d3235392d7d6e646d64616c65642c353235302d756e64676e696e6564");
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("https://cdn.moneycorp.com/Babel/fonts/moneycorp/dotsfont.eot");
            request11.Timeout = 60;
            request11.Headers.Add(new WebTestRequestHeader("Origin", "https://qa2-login.moneycorp.com"));
            request11.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("https://cdn.moneycorp.com/Babel/fonts/moneycorp/dotsfont.woff");
            request12.ThinkTime = 2;
            request12.Timeout = 60;
            request12.Headers.Add(new WebTestRequestHeader("Origin", "https://qa2-login.moneycorp.com"));
            request12.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("https://qa-ids.moneycorp.com/login/completeLogin");
            request13.Timeout = 60;
            request13.Method = "POST";
            request13.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
            request13.Headers.Add(new WebTestRequestHeader("DeviceSource", "browser_computer"));
            request13.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            StringHttpBody request13Body = new StringHttpBody();
            request13Body.ContentType = "application/json";
            request13Body.InsertByteOrderMark = false;
            request13Body.BodyString = @"{""loginToken"":""74ee7f54688a46f18f67b4dccb0ed968"",""returnUrl"":""%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DimaliClient%26redirect_uri%3Dhttps%253A%252F%252Fqa-ip.moneycorp.com%252Fcallback.html%26response_type%3Dtoken%2520id_token%26scope%3Dopenid%2520imali_api%2520malipo_api%2520philayo_api%2520user_profile%26state%3Dbf06b6b5de8c4813b7da4a3e5174eb8b%26nonce%3D418b7abe651d4032bc8b466642e13857%26acr_values%3DvalidateReferrer%2526isValidReferrer"",""character1"":""a"",""character2"":""a"",""character3"":""a"",""question"":{""hmac"":""jqNvhmp4hVvS4HMHUlnmuy4J3h86X2qzZoPkbavqtXQ="",""questionId"":""Q6"",""questionText"":""What is your place of birth?"",""requiredCharacterIndices"":[2,3,4]}}";
            request13.Body = request13Body;
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("https://cdn2.moneycorp.com/D8nq-ypo8PtYZluK");
            request14.Timeout = 60;
            request14.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request14.QueryStringParameters.Add("35ac1e4ccf27e115", "bF3tpmJjwfpgdbtyyv6kSxgCOPwIO6kZ4Djt_l--Hp1QbXhE3kqEyARXAICT0dx9Brua8u4Ds_shbNceO" +
                    "cLDkx1y00C2QNsXIf60q1kScjJSPg9R5Rs0c7W8NMnwkoghZxOnKCJa3X8oTr2hFzWsjjsaPQ8");
            request14.QueryStringParameters.Add("tp", "14560");
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("https://qa-ids.moneycorp.com/connect/authorize/callback");
            request15.Timeout = 60;
            request15.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request15.QueryStringParameters.Add("client_id", "imaliClient");
            request15.QueryStringParameters.Add("redirect_uri", "https://qa-ip.moneycorp.com/callback.html");
            request15.QueryStringParameters.Add("response_type", "token id_token");
            request15.QueryStringParameters.Add("scope", "openid imali_api malipo_api philayo_api user_profile");
            request15.QueryStringParameters.Add("state", "bf06b6b5de8c4813b7da4a3e5174eb8b");
            request15.QueryStringParameters.Add("nonce", "418b7abe651d4032bc8b466642e13857");
            request15.QueryStringParameters.Add("acr_values", "validateReferrer&isValidReferrer");
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("https://qa-ip.moneycorp.com/callback.html");
            request16.Timeout = 60;
            request16.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("https://qa-ids.moneycorp.com/.well-known/openid-configuration/jwks");
            request17.Timeout = 60;
            request17.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("https://qa-ids.moneycorp.com/connect/userinfo");
            request18.Timeout = 60;
            request18.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("https://qa-ids.moneycorp.com/connect/checksession");
            request19.Timeout = 60;
            request19.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("https://qa-imali.moneycorp.com/corporate/branding");
            request20.Timeout = 60;
            request20.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request20.Headers.Add(new WebTestRequestHeader("Expires", "-1"));
            request20.Headers.Add(new WebTestRequestHeader("X-XSS-Protection", "1"));
            request20.Headers.Add(new WebTestRequestHeader("X-Frame-Options", "SAMEORIGIN"));
            request20.Headers.Add(new WebTestRequestHeader("ActiveClientId", "478773"));
            request20.Headers.Add(new WebTestRequestHeader("DeviceSource", "browser_computer"));
            request20.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("https://qa-business.moneycorp.com/overview");
            request21.Timeout = 60;
            request21.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("https://qa-clientdiagnostics.moneycorp.com/log");
            request22.Timeout = 60;
            request22.Method = "POST";
            request22.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
            request22.Headers.Add(new WebTestRequestHeader("X-Origin", "Imali App"));
            request22.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            StringHttpBody request22Body = new StringHttpBody();
            request22Body.ContentType = "application/json";
            request22Body.InsertByteOrderMark = false;
            request22Body.BodyString = @"{""isError"":false,""appName"":""Imali App"",""message"":{""callbackRedirectUrl"":""https://qa-business.moneycorp.com/overview"",""applicationSource"":""1"",""crmContactId"":""c131a36d-43ce-e911-9163-005056806507"",""nonce"":""418b7abe651d4032bc8b466642e13857"",""timestamp"":1603285861299,""localTimeString"":""Wed Oct 21 2020 14:11:01 GMT+0100 (GMT Daylight Time)"",""message"":""Successfully Obtained Token"",""threatMetrixToken"":""TMX_TOKEN_MISSING"",""crmAccountGuid"":""CRM_ACCOUNT_GUID"",""navigatorUserAgent"":""Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; Zoom 3.6.0; rv:11.0) like Gecko"",""navigatorAppVersion"":""5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; Zoom 3.6.0; rv:11.0) like Gecko"",""navigatorAppName"":""Netscape"",""navigatorCookiesEnabled"":true,""navigatorLocale"":""en-GB"",""navigatorScreenSize"":""2560x1440"",""bundleVersion"":""/static/js/authCallback.026bfba5.js"",""browserName"":""IE"",""browserVersion"":""11.0"",""osName"":""Windows"",""osVersion"":""10"",""deviceModel"":""DEVICE_MODEL_MISSING"",""deviceVendor"":""DEVICE_VENDOR_MISSING"",""deviceType"":""DEVICE_TYPE_MISSING""},""logger"":""common-utils"",""logLevel"":0,""logMethod"":""DEBUG""}";
            request22.Body = request22Body;
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("https://qa-business.moneycorp.com/version.txt");
            request23.Timeout = 60;
            request23.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("https://qa-cdn.moneycorp.com/babel-cms/en-GB.json");
            request24.Timeout = 60;
            request24.Headers.Add(new WebTestRequestHeader("If-Modified-Since", "Wed, 21 Oct 2020 14:00:00 GMT"));
            request24.Headers.Add(new WebTestRequestHeader("If-None-Match", "W/\"0303577b2a7d61:0\""));
            request24.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("https://www.google-analytics.com/j/collect");
            request25.Timeout = 60;
            request25.Method = "POST";
            request25.Headers.Add(new WebTestRequestHeader("Content-Type", "text/plain"));
            request25.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request25.QueryStringParameters.Add("v", "1");
            request25.QueryStringParameters.Add("_v", "j86");
            request25.QueryStringParameters.Add("a", "2018986191");
            request25.QueryStringParameters.Add("t", "pageview");
            request25.QueryStringParameters.Add("_s", "1");
            request25.QueryStringParameters.Add("dl", "https://qa-business.moneycorp.com/overview");
            request25.QueryStringParameters.Add("dr", "https://qa-ip.moneycorp.com/callback.html");
            request25.QueryStringParameters.Add("ul", "en-gb");
            request25.QueryStringParameters.Add("de", "utf-8");
            request25.QueryStringParameters.Add("sd", "24-bit");
            request25.QueryStringParameters.Add("sr", "2560x1440");
            request25.QueryStringParameters.Add("vp", "1344x449");
            request25.QueryStringParameters.Add("je", "1");
            request25.QueryStringParameters.Add("fl", "32.0 r0");
            request25.QueryStringParameters.Add("_u", "QAGAAAQAAAAAAC~");
            request25.QueryStringParameters.Add("jid", "2018684273");
            request25.QueryStringParameters.Add("gjid", "2096452735");
            request25.QueryStringParameters.Add("cid", "2053285225.1587650518");
            request25.QueryStringParameters.Add("tid", "UA-5575613-2");
            request25.QueryStringParameters.Add("_gid", "2041461375.1603285838");
            request25.QueryStringParameters.Add("_r", "1");
            request25.QueryStringParameters.Add("gtm", "2wg9u15336PNZ");
            request25.QueryStringParameters.Add("z", "1109956716");
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("https://www.google-analytics.com/j/collect");
            request26.Timeout = 60;
            request26.Method = "POST";
            request26.Headers.Add(new WebTestRequestHeader("Content-Type", "text/plain"));
            request26.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request26.QueryStringParameters.Add("v", "1");
            request26.QueryStringParameters.Add("_v", "j86");
            request26.QueryStringParameters.Add("a", "2018986191");
            request26.QueryStringParameters.Add("t", "pageview");
            request26.QueryStringParameters.Add("_s", "1");
            request26.QueryStringParameters.Add("dl", "https://qa-business.moneycorp.com/overview");
            request26.QueryStringParameters.Add("dr", "https://qa-ip.moneycorp.com/callback.html");
            request26.QueryStringParameters.Add("ul", "en-gb");
            request26.QueryStringParameters.Add("de", "utf-8");
            request26.QueryStringParameters.Add("sd", "24-bit");
            request26.QueryStringParameters.Add("sr", "2560x1440");
            request26.QueryStringParameters.Add("vp", "1344x449");
            request26.QueryStringParameters.Add("je", "1");
            request26.QueryStringParameters.Add("fl", "32.0 r0");
            request26.QueryStringParameters.Add("_u", "QAGAAEQAAAAAAC~");
            request26.QueryStringParameters.Add("jid", "147932560");
            request26.QueryStringParameters.Add("gjid", "1111787655");
            request26.QueryStringParameters.Add("cid", "2053285225.1587650518");
            request26.QueryStringParameters.Add("tid", "UA-5575613-47");
            request26.QueryStringParameters.Add("_gid", "2041461375.1603285838");
            request26.QueryStringParameters.Add("_r", "1");
            request26.QueryStringParameters.Add("gtm", "2wg9u15336PNZ");
            request26.QueryStringParameters.Add("z", "1313662983");
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("https://googleads.g.doubleclick.net/pagead/viewthroughconversion/1052657741/");
            request27.Timeout = 60;
            request27.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request27.QueryStringParameters.Add("random", "1603285862894");
            request27.QueryStringParameters.Add("cv", "9");
            request27.QueryStringParameters.Add("fst", "1603285862894");
            request27.QueryStringParameters.Add("num", "1");
            request27.QueryStringParameters.Add("guid", "ON");
            request27.QueryStringParameters.Add("resp", "GooglemKTybQhCsO");
            request27.QueryStringParameters.Add("u_h", "1440");
            request27.QueryStringParameters.Add("u_w", "2560");
            request27.QueryStringParameters.Add("u_ah", "1387");
            request27.QueryStringParameters.Add("u_aw", "2560");
            request27.QueryStringParameters.Add("u_cd", "24");
            request27.QueryStringParameters.Add("u_his", "3");
            request27.QueryStringParameters.Add("u_tz", "60");
            request27.QueryStringParameters.Add("u_java", "true");
            request27.QueryStringParameters.Add("u_nplug", "2");
            request27.QueryStringParameters.Add("u_nmime", "4");
            request27.QueryStringParameters.Add("gtm", "2wg9u1");
            request27.QueryStringParameters.Add("ig", "1");
            request27.QueryStringParameters.Add("frm", "0");
            request27.QueryStringParameters.Add("url", "https://qa-business.moneycorp.com/overview");
            request27.QueryStringParameters.Add("ref", "https://qa-ip.moneycorp.com/callback.html");
            request27.QueryStringParameters.Add("hn", "www.googleadservices.com");
            request27.QueryStringParameters.Add("async", "1");
            request27.QueryStringParameters.Add("rfmt", "3");
            request27.QueryStringParameters.Add("fmt", "4");
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("https://stats.g.doubleclick.net/j/collect");
            request28.Timeout = 60;
            request28.Method = "POST";
            request28.Headers.Add(new WebTestRequestHeader("Content-Type", "text/plain"));
            request28.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request28.QueryStringParameters.Add("t", "dc");
            request28.QueryStringParameters.Add("aip", "1");
            request28.QueryStringParameters.Add("_r", "3");
            request28.QueryStringParameters.Add("v", "1");
            request28.QueryStringParameters.Add("_v", "j86");
            request28.QueryStringParameters.Add("tid", "UA-5575613-2");
            request28.QueryStringParameters.Add("cid", "2053285225.1587650518");
            request28.QueryStringParameters.Add("jid", "2018684273");
            request28.QueryStringParameters.Add("gjid", "2096452735");
            request28.QueryStringParameters.Add("_gid", "2041461375.1603285838");
            request28.QueryStringParameters.Add("_u", "QAGAAAAAAAAAAC~");
            request28.QueryStringParameters.Add("z", "2025473282");
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("https://stats.g.doubleclick.net/j/collect");
            request29.ThinkTime = 4;
            request29.Timeout = 60;
            request29.Method = "POST";
            request29.Headers.Add(new WebTestRequestHeader("Content-Type", "text/plain"));
            request29.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request29.QueryStringParameters.Add("t", "dc");
            request29.QueryStringParameters.Add("aip", "1");
            request29.QueryStringParameters.Add("_r", "3");
            request29.QueryStringParameters.Add("v", "1");
            request29.QueryStringParameters.Add("_v", "j86");
            request29.QueryStringParameters.Add("tid", "UA-5575613-47");
            request29.QueryStringParameters.Add("cid", "2053285225.1587650518");
            request29.QueryStringParameters.Add("jid", "147932560");
            request29.QueryStringParameters.Add("gjid", "1111787655");
            request29.QueryStringParameters.Add("_gid", "2041461375.1603285838");
            request29.QueryStringParameters.Add("_u", "QAGAAEQAAAAAAC~");
            request29.QueryStringParameters.Add("z", "1080324400");
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("https://qa-ids.moneycorp.com/connect/authorize");
            request30.Timeout = 60;
            request30.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request30.QueryStringParameters.Add("client_id", "imaliClient");
            request30.QueryStringParameters.Add("redirect_uri", "https://qa-business.moneycorp.com/callback.html");
            request30.QueryStringParameters.Add("response_type", "token id_token");
            request30.QueryStringParameters.Add("scope", "openid imali_api malipo_api philayo_api user_profile");
            request30.QueryStringParameters.Add("state", "be7676792f51426ba7e8d6ae7c4d398f");
            request30.QueryStringParameters.Add("nonce", "9447b05f756844e8b56aa111e1dd4e41");
            request30.QueryStringParameters.Add("acr_values", "validateReferrer&isValidReferrer");
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("https://qa-business.moneycorp.com/callback.html");
            request31.Timeout = 60;
            request31.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("https://mie.wearematterkind.com/utag/preview.html");
            request32.Timeout = 60;
            request32.Headers.Add(new WebTestRequestHeader("If-Modified-Since", "Sat, 18 May 2019 00:38:03 GMT"));
            request32.Headers.Add(new WebTestRequestHeader("If-None-Match", "\"885d1835b67454ba82b322542c09e5cd-gzip\""));
            request32.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("https://qa-ids.moneycorp.com/connect/userinfo");
            request33.Timeout = 60;
            request33.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("https://qa-ids.moneycorp.com/connect/checksession");
            request34.Timeout = 60;
            request34.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("https://qa-imali.moneycorp.com/corporate/branding");
            request35.Timeout = 60;
            request35.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request35.Headers.Add(new WebTestRequestHeader("Expires", "-1"));
            request35.Headers.Add(new WebTestRequestHeader("X-XSS-Protection", "1"));
            request35.Headers.Add(new WebTestRequestHeader("X-Frame-Options", "SAMEORIGIN"));
            request35.Headers.Add(new WebTestRequestHeader("ActiveClientId", "478773"));
            request35.Headers.Add(new WebTestRequestHeader("DeviceSource", "browser_computer"));
            request35.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("https://qa-business.moneycorp.com/overview");
            request36.Timeout = 60;
            request36.Headers.Add(new WebTestRequestHeader("If-Modified-Since", "Wed, 21 Oct 2020 09:54:52 GMT"));
            request36.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest("https://qa-clientdiagnostics.moneycorp.com/log");
            request37.Timeout = 60;
            request37.Method = "POST";
            request37.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
            request37.Headers.Add(new WebTestRequestHeader("X-Origin", "Imali App"));
            request37.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            StringHttpBody request37Body = new StringHttpBody();
            request37Body.ContentType = "application/json";
            request37Body.InsertByteOrderMark = false;
            request37Body.BodyString = @"{""isError"":false,""appName"":""Imali App"",""message"":{""callbackRedirectUrl"":""https://qa-business.moneycorp.com/overview"",""partnerName"":""moneycorp"",""applicationSource"":""1"",""crmContactId"":""c131a36d-43ce-e911-9163-005056806507"",""nonce"":""9447b05f756844e8b56aa111e1dd4e41"",""timestamp"":1603285869816,""localTimeString"":""Wed Oct 21 2020 14:11:09 GMT+0100 (GMT Daylight Time)"",""message"":""Successfully Obtained Token"",""threatMetrixToken"":""TMX_TOKEN_MISSING"",""crmAccountGuid"":""CRM_ACCOUNT_GUID"",""navigatorUserAgent"":""Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; Zoom 3.6.0; rv:11.0) like Gecko"",""navigatorAppVersion"":""5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; Zoom 3.6.0; rv:11.0) like Gecko"",""navigatorAppName"":""Netscape"",""navigatorCookiesEnabled"":true,""navigatorLocale"":""en-GB"",""navigatorScreenSize"":""2560x1440"",""bundleVersion"":""/static/js/authCallback.301dd6c3.js"",""browserName"":""IE"",""browserVersion"":""11.0"",""osName"":""Windows"",""osVersion"":""10"",""deviceModel"":""DEVICE_MODEL_MISSING"",""deviceVendor"":""DEVICE_VENDOR_MISSING"",""deviceType"":""DEVICE_TYPE_MISSING""},""logger"":""common-utils"",""logLevel"":0,""logMethod"":""DEBUG""}";
            request37.Body = request37Body;
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("https://qa-cdn.moneycorp.com/babel-cms/en-GB.json");
            request38.Timeout = 60;
            request38.Headers.Add(new WebTestRequestHeader("If-Modified-Since", "Wed, 21 Oct 2020 14:00:00 GMT"));
            request38.Headers.Add(new WebTestRequestHeader("If-None-Match", "W/\"0303577b2a7d61:0\""));
            request38.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request38;
            request38 = null;

            WebTestRequest request39 = new WebTestRequest("https://qa-ids.moneycorp.com/connect/checksession");
            request39.Timeout = 60;
            request39.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request39;
            request39 = null;

            WebTestRequest request40 = new WebTestRequest("https://qa-imali.moneycorp.com/corporate/userProfile");
            request40.Timeout = 60;
            request40.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request40.Headers.Add(new WebTestRequestHeader("Expires", "-1"));
            request40.Headers.Add(new WebTestRequestHeader("X-XSS-Protection", "1"));
            request40.Headers.Add(new WebTestRequestHeader("X-Frame-Options", "SAMEORIGIN"));
            request40.Headers.Add(new WebTestRequestHeader("ActiveClientId", "478773"));
            request40.Headers.Add(new WebTestRequestHeader("DeviceSource", "browser_computer"));
            request40.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request40;
            request40 = null;

            WebTestRequest request41 = new WebTestRequest("https://qa-imali.moneycorp.com/corporate/tasks");
            request41.Timeout = 60;
            request41.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request41.Headers.Add(new WebTestRequestHeader("Expires", "-1"));
            request41.Headers.Add(new WebTestRequestHeader("X-XSS-Protection", "1"));
            request41.Headers.Add(new WebTestRequestHeader("X-Frame-Options", "SAMEORIGIN"));
            request41.Headers.Add(new WebTestRequestHeader("ActiveClientId", "478773"));
            request41.Headers.Add(new WebTestRequestHeader("DeviceSource", "browser_computer"));
            request41.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request41;
            request41 = null;

            WebTestRequest request42 = new WebTestRequest("https://qa-clientdiagnostics.moneycorp.com/log");
            request42.Timeout = 60;
            request42.Method = "POST";
            request42.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json"));
            request42.Headers.Add(new WebTestRequestHeader("X-Origin", "Imali App"));
            request42.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            StringHttpBody request42Body = new StringHttpBody();
            request42Body.ContentType = "application/json";
            request42Body.InsertByteOrderMark = false;
            request42Body.BodyString = @"{""isError"":false,""appName"":""Imali App"",""message"":{""moneycorpCrmAccountGuid"":""bc31a36d-43ce-e911-9163-005056806507"",""partnerName"":""moneycorp"",""applicationSource"":""1"",""crmContactId"":""c131a36d-43ce-e911-9163-005056806507"",""nonce"":""9447b05f756844e8b56aa111e1dd4e41"",""timestamp"":1603285875394,""localTimeString"":""Wed Oct 21 2020 14:11:15 GMT+0100 (GMT Daylight Time)"",""message"":""Imali Corporate started"",""threatMetrixToken"":""TMX_TOKEN_MISSING"",""crmAccountGuid"":""bc31a36d-43ce-e911-9163-005056806507"",""navigatorUserAgent"":""Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; Zoom 3.6.0; rv:11.0) like Gecko"",""navigatorAppVersion"":""5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0; Zoom 3.6.0; rv:11.0) like Gecko"",""navigatorAppName"":""Netscape"",""navigatorCookiesEnabled"":true,""navigatorLocale"":""en-GB"",""navigatorScreenSize"":""2560x1440"",""bundleVersion"":""/static/js/bundle.3172d82a.js"",""browserName"":""IE"",""browserVersion"":""11.0"",""osName"":""Windows"",""osVersion"":""10"",""deviceModel"":""DEVICE_MODEL_MISSING"",""deviceVendor"":""DEVICE_VENDOR_MISSING"",""deviceType"":""DEVICE_TYPE_MISSING""},""logger"":""common-utils"",""logLevel"":0,""logMethod"":""DEBUG""}";
            request42.Body = request42Body;
            yield return request42;
            request42 = null;

            WebTestRequest request43 = new WebTestRequest("https://qa-imali.moneycorp.com/corporate/tradableCurrencies");
            request43.Timeout = 60;
            request43.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request43.Headers.Add(new WebTestRequestHeader("Expires", "-1"));
            request43.Headers.Add(new WebTestRequestHeader("X-XSS-Protection", "1"));
            request43.Headers.Add(new WebTestRequestHeader("X-Frame-Options", "SAMEORIGIN"));
            request43.Headers.Add(new WebTestRequestHeader("ActiveClientId", "478773"));
            request43.Headers.Add(new WebTestRequestHeader("DeviceSource", "browser_computer"));
            request43.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request43;
            request43 = null;

            WebTestRequest request44 = new WebTestRequest("https://qa-imali.moneycorp.com/corporate/tradableCurrencies");
            request44.Timeout = 60;
            request44.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request44.Headers.Add(new WebTestRequestHeader("Expires", "-1"));
            request44.Headers.Add(new WebTestRequestHeader("X-XSS-Protection", "1"));
            request44.Headers.Add(new WebTestRequestHeader("X-Frame-Options", "SAMEORIGIN"));
            request44.Headers.Add(new WebTestRequestHeader("ActiveClientId", "478773"));
            request44.Headers.Add(new WebTestRequestHeader("DeviceSource", "browser_computer"));
            request44.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request44;
            request44 = null;

            WebTestRequest request45 = new WebTestRequest("https://qa-imali.moneycorp.com/corporate/clientFunds");
            request45.Timeout = 60;
            request45.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request45.Headers.Add(new WebTestRequestHeader("Expires", "-1"));
            request45.Headers.Add(new WebTestRequestHeader("X-XSS-Protection", "1"));
            request45.Headers.Add(new WebTestRequestHeader("X-Frame-Options", "SAMEORIGIN"));
            request45.Headers.Add(new WebTestRequestHeader("ActiveClientId", "478773"));
            request45.Headers.Add(new WebTestRequestHeader("DeviceSource", "browser_computer"));
            request45.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request45;
            request45 = null;

            WebTestRequest request46 = new WebTestRequest("https://qa-imali.moneycorp.com/corporate/associatedClientBalances");
            request46.Timeout = 60;
            request46.Headers.Add(new WebTestRequestHeader("Pragma", "no-cache"));
            request46.Headers.Add(new WebTestRequestHeader("Expires", "-1"));
            request46.Headers.Add(new WebTestRequestHeader("X-XSS-Protection", "1"));
            request46.Headers.Add(new WebTestRequestHeader("X-Frame-Options", "SAMEORIGIN"));
            request46.Headers.Add(new WebTestRequestHeader("ActiveClientId", "478773"));
            request46.Headers.Add(new WebTestRequestHeader("DeviceSource", "browser_computer"));
            request46.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            yield return request46;
            request46 = null;

            WebTestRequest request47 = new WebTestRequest("https://qa-philayo.moneycorp.com/liverates/negotiate");
            request47.Timeout = 60;
            request47.Method = "POST";
            request47.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request47.Headers.Add(new WebTestRequestHeader("Content-Type", "text/plain;charset=UTF-8"));
            request47.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request47.QueryStringParameters.Add("activeclientid", "478773");
            request47.QueryStringParameters.Add("token", @"eyJhbGciOiJSUzI1NiIsImtpZCI6IlZfOFpIRGlLWnRObXhxd2N5OXMwWXVfMHJTMCIsInR5cCI6IkpXVCIsIng1dCI6IlZfOFpIRGlLWnRObXhxd2N5OXMwWXVfMHJTMCJ9.eyJuYmYiOjE2MDMyODU4NjcsImV4cCI6MTYwMzI4NjE2NywiaXNzIjoiaHR0cHM6Ly9xYS1pZHMubW9uZXljb3JwLmNvbSIsImF1ZCI6WyJodHRwczovL3FhLWlkcy5tb25leWNvcnAuY29tL3Jlc291cmNlcyIsImltYWxpX2FwaSIsIm1hbGlwb19hcGkiLCJwaGlsYXlvX2FwaSJdLCJjbGllbnRfaWQiOiJpbWFsaUNsaWVudCIsInN1YiI6ImMxMzFhMzZkLTQzY2UtZTkxMS05MTYzLTAwNTA1NjgwNjUwNyIsImF1dGhfdGltZSI6MTYwMzI4NTg2MCwiaWRwIjoibG9jYWwiLCJDbGllbnRJZCI6IjQ3ODc3MyIsIkNvbnRhY3RJZCI6IjYyMTU4OSIsIkFwcGxpY2F0aW9uU291cmNlIjoiMSIsIklzQ2xpZW50QXV0aG9yaXNlZCI6IlRydWUiLCJJc0NvcnBvcmF0ZSI6IkZhbHNlIiwiSXNBZHZhbmNlZCI6IlRydWUiLCJDcm1Db250YWN0SWQiOiJjMTMxYTM2ZC00M2NlLWU5MTEtOTE2My0wMDUwNTY4MDY1MDciLCJVc2VyTmFtZSI6IlBVc2VyMSIsIklzTUZBRW5hYmxlZCI6IkZhbHNlIiwic19oYXNoIjoibUk2QmlfbzVtSVhEUHJXNVotVHkyUSIsInNjb3BlIjpbIm9wZW5pZCIsInVzZXJfcHJvZmlsZSIsImltYWxpX2FwaSIsIm1hbGlwb19hcGkiLCJwaGlsYXlvX2FwaSJdLCJhbXIiOlsicHdkIl19.DZO0UIzZ-Z4mAXbnyeESXNeEDIbEcQXvkn5WrRCgr31eq62cMBy5nqSSjfCrHrmRnxdc78PyUjccOOnxeo1a01WSWN3uPnxp2mQ7iUEJBd7-lsRz7x9kmJebXeEFNtgWEB8Y1wMf5yVKeAN-UpbGFKnSgvoaLlO38MoarRGnSoWcXjr-VHBaCYotVIUbieiZYdqO_A9N4Io6Bxm5fdTYihzG_MGVBysKJyVnZjoxdKBvJ47A9XvEWuVXWSBw70VUpGu-7hCs5UlzIQftZuI2kQKkj_sAgqgTZpx4oBBcuwijhwPJGvfKLKiXzDDJEQXQxVtPctooG9N9aFSxXNqsBQ");
            request47.QueryStringParameters.Add("negotiateVersion", "1");
            yield return request47;
            request47 = null;

            WebTestRequest request48 = new WebTestRequest("https://qa-philayo.moneycorp.com/liverates");
            request48.Timeout = 60;
            request48.Headers.Add(new WebTestRequestHeader("Origin", "https://qa-business.moneycorp.com"));
            request48.Headers.Add(new WebTestRequestHeader("Sec-WebSocket-Key", "ikLu3ImB2LO9g3IqEAqshw=="));
            request48.Headers.Add(new WebTestRequestHeader("Upgrade", "websocket"));
            request48.Headers.Add(new WebTestRequestHeader("Sec-WebSocket-Version", "13"));
            request48.Headers.Add(new WebTestRequestHeader("DNT", "1"));
            request48.QueryStringParameters.Add("activeclientid", "478773");
            request48.QueryStringParameters.Add("token", @"eyJhbGciOiJSUzI1NiIsImtpZCI6IlZfOFpIRGlLWnRObXhxd2N5OXMwWXVfMHJTMCIsInR5cCI6IkpXVCIsIng1dCI6IlZfOFpIRGlLWnRObXhxd2N5OXMwWXVfMHJTMCJ9.eyJuYmYiOjE2MDMyODU4NjcsImV4cCI6MTYwMzI4NjE2NywiaXNzIjoiaHR0cHM6Ly9xYS1pZHMubW9uZXljb3JwLmNvbSIsImF1ZCI6WyJodHRwczovL3FhLWlkcy5tb25leWNvcnAuY29tL3Jlc291cmNlcyIsImltYWxpX2FwaSIsIm1hbGlwb19hcGkiLCJwaGlsYXlvX2FwaSJdLCJjbGllbnRfaWQiOiJpbWFsaUNsaWVudCIsInN1YiI6ImMxMzFhMzZkLTQzY2UtZTkxMS05MTYzLTAwNTA1NjgwNjUwNyIsImF1dGhfdGltZSI6MTYwMzI4NTg2MCwiaWRwIjoibG9jYWwiLCJDbGllbnRJZCI6IjQ3ODc3MyIsIkNvbnRhY3RJZCI6IjYyMTU4OSIsIkFwcGxpY2F0aW9uU291cmNlIjoiMSIsIklzQ2xpZW50QXV0aG9yaXNlZCI6IlRydWUiLCJJc0NvcnBvcmF0ZSI6IkZhbHNlIiwiSXNBZHZhbmNlZCI6IlRydWUiLCJDcm1Db250YWN0SWQiOiJjMTMxYTM2ZC00M2NlLWU5MTEtOTE2My0wMDUwNTY4MDY1MDciLCJVc2VyTmFtZSI6IlBVc2VyMSIsIklzTUZBRW5hYmxlZCI6IkZhbHNlIiwic19oYXNoIjoibUk2QmlfbzVtSVhEUHJXNVotVHkyUSIsInNjb3BlIjpbIm9wZW5pZCIsInVzZXJfcHJvZmlsZSIsImltYWxpX2FwaSIsIm1hbGlwb19hcGkiLCJwaGlsYXlvX2FwaSJdLCJhbXIiOlsicHdkIl19.DZO0UIzZ-Z4mAXbnyeESXNeEDIbEcQXvkn5WrRCgr31eq62cMBy5nqSSjfCrHrmRnxdc78PyUjccOOnxeo1a01WSWN3uPnxp2mQ7iUEJBd7-lsRz7x9kmJebXeEFNtgWEB8Y1wMf5yVKeAN-UpbGFKnSgvoaLlO38MoarRGnSoWcXjr-VHBaCYotVIUbieiZYdqO_A9N4Io6Bxm5fdTYihzG_MGVBysKJyVnZjoxdKBvJ47A9XvEWuVXWSBw70VUpGu-7hCs5UlzIQftZuI2kQKkj_sAgqgTZpx4oBBcuwijhwPJGvfKLKiXzDDJEQXQxVtPctooG9N9aFSxXNqsBQ");
            request48.QueryStringParameters.Add("id", "RLH_EKd8MPt49e7dajmCPA");
            yield return request48;
            request48 = null;
        }
    }
}
